# Generated by Django 2.2.1 on 2019-05-24 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='Not Specified', max_length=20)),
                ('asset_type', models.CharField(default='Not Specified', max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None submitted', max_length=20)),
                ('floor', models.IntegerField()),
                ('has_tv', models.BooleanField()),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karoom.RoomAssets')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=0.5)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karoom.Room')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
