# Generated by Django 2.2.1 on 2019-05-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomAssets',
            new_name='RoomAsset',
        ),
    ]
