# Generated by Django 2.2.1 on 2019-05-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karoom', '0002_auto_20190524_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karoom.Room'),
        ),
    ]
